name: JVSR_base
scale: 4
N: 2 # temporal_radius

dataset:
  name: REDS
  path: /workspace/datasets/REDS
  batch_size: 32
  GT_size: 256 # LR_size = GT_size // scale

train:
  beta1: 0.9
  beta2: 0.99
  lr: 0.0002
  num_epochs: 1

arch:
  alignment:
    level: 3
  reconstruction:
    block: 5
